import mongoose from "mongoose";
import {
  arrayObjectId,
  dataId,
  dataNumber,
  dataNumberReq,
  dataString,
} from "../controllers/setup";
const PeeCampSchema = new mongoose.Schema({
  campId: dataId,
  question: dataString,
  a: dataString,
  b: dataString,
  c: dataString,
  d: dataString,
  e: dataString,
  scoreA: dataNumberReq,
  scoreB: dataNumberReq,
  scoreC: dataNumberReq,
  scoreD: dataNumberReq,
  scoreE: dataNumberReq,
  nongAnswerA: dataNumber,
  nongAnswerB: dataNumber,
  nongAnswerC: dataNumber,
  nongAnswerD: dataNumber,
  nongAnswerE: dataNumber,
  peeAnswerA: dataNumber,
  peeAnswerB: dataNumber,
  peeAnswerC: dataNumber,
  peeAnswerD: dataNumber,
  peeAnswerE: dataNumber,
  correct: {
    type: String,
    required: true,
    enum: ["A", "B", "C", "D", "E", "-"],
  },
  order: dataNumberReq,
  answerIds: arrayObjectId,
});
export default mongoose.model("ChoiceQuestion", PeeCampSchema);
