//*export async function getBaan
//*export async function getCamp
//*export async function getBaans
//*export async function getCamps
//*export async function getNongCamp
//*export async function getPeeCamp
//*export async function getPetoCamp
//*export async function getPart
//*export async function addNong
//*export async function addPee
//*export async function addPeeRaw
// export async function addPeto
//*export async function addPetoRaw
//*export async function staffRegister
//*export async function getActionPlanByPartId
//*export async function createActionPlan
//*export async function updateActionPlan
//*export async function deleteActionPlan
//*export async function getActionPlans
//*export async function nongRegister
//*export async function getCampName
//*export async function getPartName
//*export async function changeBaan
//*export async function changeBaanRaw
//*export async function changePart
//*export async function changePartRaw
//*export async function getNongsFromBaanId
//*export async function getPeesFromBaanId
//*export async function getPeesFromPartId
//*export async function getPetosFromPartId
// export async function getLinkRegister
//*export async function getImpotentPartIdBCRP
//*export async function getActionPlan
//*export async function getWorkingItemByPartId
//*export async function createWorkingItem
//*export async function updateWorkingItem
//*export async function deleteWorkingItem
//*export async function getWorkingItems
//*export async function getWorkingItem
//*export async function getShowRegisters
//*export async function getAllUserCamp
//*export async function getAllWelfare
//*export async function getAllPlanData
//*export async function planUpdateCamp
//*export async function editQuestion
//*export async function getAllQuestion
//*export async function answerAllQuestion
//*export async function deleteChoiceQuestion
//*export async function deleteTextQuestion
//*export async function peeAnswerQuestion
//*export async function plusActionPlan
//*export async function getAllAnswerAndQuestion
//*export async function scoreTextQuestions
// export async function getHealthIssueForAct
// export async function getMedicalHealthIssue
//*export async function getCoopData
//*export async function getAllNongRegister
//*export async function getActionPlanByCampId
//*export async function getWorkingItemByCampId
//*export async function getParts
//*export async function getNongCampData
//*export async function getPeeCampData
//*export async function getPetoCampData
//*export async function getPartForUpdate
//*export async function getRegisterData
//*export async function getCampState
